# ===================================
#  List Behavior Config
# ===================================

title: bnb.usergroup::lang.groups.list_title
list: ~/plugins/bnb/usergroup/models/usergroup/columns.yaml
modelClass: BnB\UserGroup\Models\UserGroup
recordUrl: bnb/usergroup/usergroups/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



